# Generated by Django 5.0.6 on 2025-07-29 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HiringPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="hiring_partners_logos/")),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_creation_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
