# Generated by Django 5.0.6 on 2025-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_heading_hiringpartner_alter_user_contact_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GettingStartedStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="getting_started/")),
                ("alt", models.CharField(max_length=100)),
                ("is_html", models.BooleanField(default=False)),
            ],
        ),
    ]
