# Generated by Django 5.0.6 on 2025-07-29 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rolesectionheading_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="section",
        ),
    ]
