# Generated by Django 5.0.6 on 2025-07-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_role_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepresentingCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="representing_companies/")),
            ],
        ),
        migrations.CreateModel(
            name="RepresentingCompanyHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.TextField(blank=True)),
            ],
        ),
    ]
