# Generated by Django 5.0.6 on 2025-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_representingcompany_representingcompanyheading"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("companyColor", models.CharField(max_length=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
            ],
        ),
    ]
