# Generated by Django 5.0.6 on 2025-07-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("icon", models.ImageField(upload_to="icons/")),
            ],
        ),
    ]
