# Generated by Django 5.0.6 on 2025-07-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_advantage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge", models.CharField(max_length=255)),
                ("old_price", models.CharField(max_length=50)),
                ("new_price", models.CharField(max_length=50)),
                ("note", models.TextField()),
                ("cta_text", models.CharField(max_length=255)),
                ("cta_link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="OfferFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="app.offer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferTrustedBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="trusted_logos/")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logos",
                        to="app.offer",
                    ),
                ),
            ],
        ),
    ]
