# Generated by Django 5.0.6 on 2025-07-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_offer_offerfeature_offertrustedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="cta_link",
            field=models.CharField(max_length=100),
        ),
    ]
