# Generated by Django 5.0.6 on 2025-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_offer_cta_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="offertrustedby",
            name="TrustedText",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
