# Generated by Django 5.0.6 on 2025-07-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_offertrustedby_trustedtext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offertrustedby",
            name="TrustedText",
        ),
        migrations.AddField(
            model_name="offer",
            name="logoHeading",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
