# Generated by Django 5.0.6 on 2025-07-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_remove_offertrustedby_trustedtext_offer_logoheading"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
