# Generated by Django 5.0.6 on 2025-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_logintestimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginQuotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="LoginQuotes/")),
            ],
        ),
        migrations.DeleteModel(
            name="LoginTestimonial",
        ),
    ]
