# Generated by Django 5.0.6 on 2025-07-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_loginquotes_delete_logintestimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=100)),
                ("company_website", models.URLField()),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "IT"),
                            ("Finance", "Finance"),
                            ("Marketing", "Marketing"),
                            ("Healthcare", "Healthcare"),
                            ("Education", "Education"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sub_industry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("Private", "Private"), ("Public", "Public")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "stage_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10-50", "10-50"),
                            ("50-100", "50-100"),
                            ("100-500", "100-500"),
                            ("500-1000", "500-1000"),
                            ("1000+", "1000+"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("founded_in", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        choices=[("B2B", "B2B"), ("B2C", "B2C"), ("D2C", "D2C")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "about_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
