# Generated by Django 5.0.6 on 2025-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="mobile",
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="role",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
