# Generated by Django 5.0.6 on 2025-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_workspace_mobile_workspace_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="mobile",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
