# Generated by Django 5.0.6 on 2025-08-04 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_workspace_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="stage_size",
            new_name="size",
        ),
    ]
