# Generated by Django 5.0.6 on 2025-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_rename_stage_size_workspace_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="about_founders",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
