# Generated by Django 5.0.6 on 2025-08-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_workspace_about_founders"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="workspace",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("experience_min", models.PositiveIntegerField()),
                ("experience_max", models.PositiveIntegerField()),
                ("number_of_openings", models.PositiveIntegerField()),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("growth", "Growth"),
                            ("strategy", "Strategy"),
                            ("marketing", "Marketing"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("compensation_lpa", models.FloatField()),
                ("is_compensation_negotiable", models.BooleanField(default=False)),
                ("esops_lpa", models.FloatField()),
                ("roles_responsibilities", models.TextField()),
                ("qualifications", models.TextField()),
                (
                    "mode_of_work",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("on_site", "On-Site"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "work_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("variable_lpa", models.FloatField(blank=True, null=True)),
                ("interview_process", models.TextField(blank=True, null=True)),
                ("plan_30_60_90", models.TextField(blank=True, null=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="app.workspace",
                    ),
                ),
                ("non_negotiable_skills", models.ManyToManyField(to="app.skill")),
            ],
        ),
    ]
