# Generated by Django 5.0.6 on 2025-08-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_skill_alter_workspace_email_jobposting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.workspace"
            ),
        ),
    ]
