# Generated by Django 5.0.6 on 2025-08-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_alter_jobposting_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings",
                to="app.workspace",
            ),
        ),
    ]
