# Generated by Django 5.0.6 on 2025-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_alter_jobposting_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
