# Generated by Django 5.0.6 on 2025-08-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_jobposting_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
