# Generated by Django 5.0.6 on 2025-08-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_jobposting_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time_permanent", "Full Time - Permanent"),
                    ("full_time_contract", "Full Time - Temporary/Contractual"),
                    ("full_time_freelance", "Full Time - Freelance/Home Based"),
                    ("part_time_permanent", "Part Time - Permanent"),
                    ("part_time_contract", "Part Time - Temporary/Contractual"),
                    ("part_time_freelance", "Part Time - Freelance/Home Based"),
                ],
                default="full_time_permanent",
                max_length=50,
            ),
        ),
    ]
