# Generated by Django 5.0.6 on 2025-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_jobposting_employment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="function",
            field=models.CharField(
                choices=[
                    ("IT", "IT"),
                    ("Finance", "Finance"),
                    ("Healthcare", "Healthcare"),
                    ("Education", "Education"),
                    ("product", "Product"),
                    ("growth", "Growth"),
                    ("strategy", "Strategy"),
                    ("marketing", "Marketing"),
                    ("others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
