# Generated by Django 5.0.6 on 2025-09-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_alter_jobposting_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("expected_ctc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notice_period", models.PositiveIntegerField()),
                ("resume", models.FileField(upload_to="resumes/")),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="app.jobposting",
                    ),
                ),
            ],
        ),
    ]
