from django.urls import path

from .views import *
urlpatterns = [
    path('signup/', SignupAPIView.as_view()),
    path('login/', LoginAPIView.as_view()),
    path('refresh/', TokenAPIVIew.as_view()),
    path('user/', UserAPIView.as_view()),
    path('send-otp/', PasswordResetAPIView.as_view(), name='send_otp'),
    path('update-password/', PasswordResetAPIView.as_view(), name='update_password'),
    path('verify-otp/', PasswordResetAPIView.as_view(), name='verify_otp'),
    path("google-login/", GoogleLoginView.as_view(), name="google-login"),
    path("linkedin-login/", LinkedInLoginView.as_view(), name="linkedin-login"),
    path("hiring-partners/", HiringPartnersView.as_view(), name='hiring-partners'),
    path('getting-started/', GettingStartedStepsView.as_view(),
         name='getting-started'),
    path('roles/', RolesView.as_view(), name='roles-section'),
    path('representing-companies/', RepresentingCompanyView.as_view(),
         name='representing-companies'),
    path('testimonial/', GetTestimonial.as_view(), name='get-testimonial'),
    path('Advantages/', Advantages.as_view(), name='Advantages'),
    path('offer/', GetOffer.as_view(), name='get_offer'),
    path("faqs/", FAQView.as_view(), name="faq-view"),
    path("LoginQuotes/", LoginQuotesView.as_view(),
         name="LoginQuotes"),
    path("workspace/", WorkspaceView.as_view(), name="workspace"),
    path('update-workspace-role/',
         UpdateWorkspaceView.as_view(), name='update-workspace'),
    path('job-postings/', JobPostingCreateView.as_view(),
         name='create-job-posting'),
    path("workspaces/domain/", DomainWorkspaceView.as_view(),
         name="workspace-by-domain"),
    path('jobs/', JobPostingListView.as_view(), name='job-postings-list'),
    path('jobs/<int:job_id>/', JobPostingListView.as_view(), name='job-detail'),
    path('job-posting/choices/', JobPostingChoicesView.as_view(),
         name='job-posting-choices'),
    path('apply/<int:job_id>/', ApplyJobAPIView.as_view(), name='apply-job'),
    path('jobs/<int:job_id>/candidates/',
         ApplyJobAPIView.as_view(), name='applied_candidates'),
]
